spring.datasource.url=jdbc:postgresql://localhost:5432/TelegramBot_BD
spring.datasource.username=Telegram_user
spring.datasource.password=xxx
telegram.bot.token=xxx
spring.liquibase.change-log=classpath:liquibase/changelog-master.yaml
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.liquibase.enabled=true

