spring.datasource.url= jdbc:postgresql://localhost:5432/TelegramBot_BD
spring.datasource.username= Telegram_user
spring.datasource.password= 000007
telegram.bot.token= 8154719078:AAHWEri2LFCOy1z7qNxP7ACcnlwp3sQYktE
